.PHONY = clean
clean:
	find . -type f -not -name "make.exe" -not -name "make" -not -name "makefile" -print0 |xargs -0 rm
pottery :
	@ > pottery
	@echo "pottery"
irrigation : pottery
	@ > irrigation
	@echo "irrigation"
writing : pottery
	@ > writing
	@echo "writing"
animal_husbandry :
	@ > animal_husbandry
	@echo "animal_husbandry"
archery : animal_husbandry
	@ > archery
	@echo "archery"
mining :
	@ > mining
	@echo "mining"
masonry : mining
	@ > masonry
	@echo "masonry"
bronze_working : mining
	@ > bronze_working
	@echo "bronze_working"
the_wheel : mining
	@ > the_wheel
	@echo "the_wheel"
apprenticeship : mining currency horseback_riding
	@ > apprenticeship
	@echo "apprenticeship"
sailing :
	@ > sailing
	@echo "sailing"
celestial_navigation : sailing astrology
	@ > celestial_navigation
	@echo "celestial_navigation"
shipbuilding : sailing
	@ > shipbuilding
	@echo "shipbuilding"
astrology :
	@ > astrology
	@echo "astrology"
drama_poetry : astrology irrigation masonry early_empire mysticism
	@ > drama_poetry
	@echo "drama_poetry"
theology : astrology mysticism drama_poetry
	@ > theology
	@echo "theology"
horseback_riding : archery
	@ > horseback_riding
	@echo "horseback_riding"
machinery : archery iron_working engineering
	@ > machinery
	@echo "machinery"
currency : writing foreign_trade
	@ > currency
	@echo "currency"
state_workforce : writing bronze_working craftsmanship
	@ > state_workforce
	@echo "state_workforce"
recorded_history : writing political_philosophy drama_poetry
	@ > recorded_history
	@echo "recorded_history"
construction : masonry the_wheel horseback_riding
	@ > construction
	@echo "construction"
engineering : masonry the_wheel
	@ > engineering
	@echo "engineering"
iron_working : bronze_working
	@ > iron_working
	@echo "iron_working"
mathematics : bronze_working celestial_navigation currency drama_poetry
	@ > mathematics
	@echo "mathematics"
military_training : bronze_working military_tradition games_recreation
	@ > military_training
	@echo "military_training"
cartography : celestial_navigation shipbuilding
	@ > cartography
	@echo "cartography"
medieval_faires : currency feudalism
	@ > medieval_faires
	@echo "medieval_faires"
guilds : currency feudalism civil_service
	@ > guilds
	@echo "guilds"
mercantilism : currency humanism
	@ > mercantilism
	@echo "mercantilism"
stirrups : horseback_riding feudalism
	@ > stirrups
	@echo "stirrups"
mass_production : shipbuilding machinery education
	@ > mass_production
	@echo "mass_production"
naval_tradition : shipbuilding defensive_tactics
	@ > naval_tradition
	@echo "naval_tradition"
military_tactics : mathematics
	@ > military_tactics
	@echo "military_tactics"
education : mathematics apprenticeship
	@ > education
	@echo "education"
military_engineering : construction engineering
	@ > military_engineering
	@echo "military_engineering"
castles : construction divine_right exploration
	@ > castles
	@echo "castles"
games_recreation : construction state_workforce
	@ > games_recreation
	@echo "games_recreation"
gunpowder : apprenticeship stirrups military_engineering
	@ > gunpowder
	@echo "gunpowder"
printing : machinery education
	@ > printing
	@echo "printing"
metal_casting : machinery gunpowder
	@ > metal_casting
	@echo "metal_casting"
banking : education stirrups guilds
	@ > banking
	@echo "banking"
astronomy : education
	@ > astronomy
	@echo "astronomy"
military_science : stirrups printing siege_tactics
	@ > military_science
	@echo "military_science"
siege_tactics : castles metal_casting
	@ > siege_tactics
	@echo "siege_tactics"
square_rigging : cartography gunpowder
	@ > square_rigging
	@echo "square_rigging"
exploration : cartography mercenaries medieval_faires
	@ > exploration
	@echo "exploration"
industrialization : mass_production square_rigging
	@ > industrialization
	@echo "industrialization"
scientific_theory : banking astronomy the_enlightenment
	@ > scientific_theory
	@echo "scientific_theory"
colonialism : astronomy mercantilism
	@ > colonialism
	@echo "colonialism"
ballistics : metal_casting siege_tactics
	@ > ballistics
	@echo "ballistics"
economics : metal_casting scientific_theory
	@ > economics
	@echo "economics"
scorched_earth : metal_casting nationalism
	@ > scorched_earth
	@echo "scorched_earth"
steam_power : industrialization
	@ > steam_power
	@echo "steam_power"
flight : industrialization scientific_theory economics
	@ > flight
	@echo "flight"
steel : industrialization rifling
	@ > steel
	@echo "steel"
class_struggle : industrialization ideology
	@ > class_struggle
	@echo "class_struggle"
sanitation : scientific_theory urbanization
	@ > sanitation
	@echo "sanitation"
rifling : ballistics military_science
	@ > rifling
	@echo "rifling"
totalitarianism : military_science ideology
	@ > totalitarianism
	@echo "totalitarianism"
electricity : steam_power mercantilism
	@ > electricity
	@echo "electricity"
radio : steam_power flight conservation
	@ > radio
	@echo "radio"
chemistry : sanitation
	@ > chemistry
	@echo "chemistry"
suffrage : sanitation ideology
	@ > suffrage
	@echo "suffrage"
replaceable_parts : economics
	@ > replaceable_parts
	@echo "replaceable_parts"
capitalism : economics mass_media
	@ > capitalism
	@echo "capitalism"
combined_arms : flight combustion
	@ > combined_arms
	@echo "combined_arms"
synthetic_materials : flight plastics
	@ > synthetic_materials
	@echo "synthetic_materials"
rapid_deployment : flight cold_war
	@ > rapid_deployment
	@echo "rapid_deployment"
advanced_ballistics : replaceable_parts steel electricity
	@ > advanced_ballistics
	@echo "advanced_ballistics"
combustion : steel natural_history
	@ > combustion
	@echo "combustion"
computers : electricity radio suffrage totalitarianism class_struggle
	@ > computers
	@echo "computers"
advanced_flight : radio
	@ > advanced_flight
	@echo "advanced_flight"
rocketry : radio chemistry
	@ > rocketry
	@echo "rocketry"
nanotechnology : radio composites
	@ > nanotechnology
	@echo "nanotechnology"
mass_media : radio urbanization
	@ > mass_media
	@echo "mass_media"
nuclear_program : chemistry ideology
	@ > nuclear_program
	@echo "nuclear_program"
plastics : combustion
	@ > plastics
	@echo "plastics"
satellites : advanced_flight rocketry
	@ > satellites
	@echo "satellites"
globalization : advanced_flight rapid_deployment space_race
	@ > globalization
	@echo "globalization"
guidance_systems : rocketry advanced_ballistics
	@ > guidance_systems
	@echo "guidance_systems"
space_race : rocketry cold_war
	@ > space_race
	@echo "space_race"
nuclear_fission : advanced_ballistics combined_arms
	@ > nuclear_fission
	@echo "nuclear_fission"
telecommunications : computers
	@ > telecommunications
	@echo "telecommunications"
robotics : computers globalization
	@ > robotics
	@echo "robotics"
lasers : nuclear_fission
	@ > lasers
	@echo "lasers"
cold_war : nuclear_fission ideology
	@ > cold_war
	@echo "cold_war"
composites : synthetic_materials
	@ > composites
	@echo "composites"
stealth_technology : synthetic_materials
	@ > stealth_technology
	@echo "stealth_technology"
social_media : telecommunications professional_sports space_race
	@ > social_media
	@echo "social_media"
nuclear_fusion : lasers
	@ > nuclear_fusion
	@echo "nuclear_fusion"
code_of_laws :
	@ > code_of_laws
	@echo "code_of_laws"
craftsmanship : code_of_laws
	@ > craftsmanship
	@echo "craftsmanship"
foreign_trade : code_of_laws
	@ > foreign_trade
	@echo "foreign_trade"
military_tradition : craftsmanship
	@ > military_tradition
	@echo "military_tradition"
early_empire : foreign_trade
	@ > early_empire
	@echo "early_empire"
mysticism : foreign_trade
	@ > mysticism
	@echo "mysticism"
political_philosophy : state_workforce early_empire
	@ > political_philosophy
	@echo "political_philosophy"
defensive_tactics : games_recreation political_philosophy
	@ > defensive_tactics
	@echo "defensive_tactics"
humanism : drama_poetry medieval_faires
	@ > humanism
	@echo "humanism"
mercenaries : military_training feudalism
	@ > mercenaries
	@echo "mercenaries"
feudalism : defensive_tactics
	@ > feudalism
	@echo "feudalism"
civil_service : defensive_tactics recorded_history
	@ > civil_service
	@echo "civil_service"
divine_right : theology civil_service
	@ > divine_right
	@echo "divine_right"
diplomatic_service : guilds
	@ > diplomatic_service
	@echo "diplomatic_service"
reformed_church : guilds divine_right
	@ > reformed_church
	@echo "reformed_church"
the_enlightenment : humanism diplomatic_service
	@ > the_enlightenment
	@echo "the_enlightenment"
civil_engineering : mercantilism
	@ > civil_engineering
	@echo "civil_engineering"
nationalism : the_enlightenment
	@ > nationalism
	@echo "nationalism"
opera_ballet : the_enlightenment
	@ > opera_ballet
	@echo "opera_ballet"
natural_history : colonialism
	@ > natural_history
	@echo "natural_history"
urbanization : civil_engineering nationalism
	@ > urbanization
	@echo "urbanization"
conservation : natural_history urbanization
	@ > conservation
	@echo "conservation"
mobilization : urbanization
	@ > mobilization
	@echo "mobilization"
cultural_heritage : conservation
	@ > cultural_heritage
	@echo "cultural_heritage"
ideology : mass_media mobilization
	@ > ideology
	@echo "ideology"
professional_sports : ideology
	@ > professional_sports
	@echo "professional_sports"
